# Generated by Django 5.2.8 on 2025-11-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('Department', models.CharField(max_length=40)),
                ('Designation', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact_no', models.CharField(blank=True, max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
