# Generated by Django 5.2.8 on 2025-11-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
